### ISSUE TITLE
Problems with a method extjs_fieldset

### ISSUE THREAD

**Issue by nickolay-gvfs** [extjs/mvc#3]
At the method announcement the exception is always thrown out:

NoMethodError: undefined method `extjs_fieldset'.

Always at use extjs_fields

**Comment by christocracy** [comment]
Hi just did a big
merge.  I'll look into it, thanks.

**Comment by christocracy** [comment]
Are you including the ExtJS::Model mixin in your model?

See the README

include ExtJS::Model

**Comment by nickolay-gvfs** [comment]
Hi! Yes, I include ExtJS::Model in model. But extjs_fields its works.

**Comment by nickolay-gvfs** [comment]
Thanks! I have solved a problem! I simply had old version 0.2.8, but after installation version 0.3 all work.

**Comment by christocracy** [comment]
Thanks.
