### ISSUE TITLE
0.3.5 does not work with namespaced controllers

### ISSUE THREAD

**Issue by durchanek** [extjs/mvc#4]
Problem is obviously in extjs/data/store.rb, line 116, instead of
    proxy["url"] = "/#{@controller.controller_name}.#{@format.to_s}"
there should be
    proxy["url"] = "/#{@controller.controller_path}.#{@format.to_s}"

**Comment by christocracy** [comment]
Ok, I wasn't even aware of controller_path.

**Comment by christocracy** [comment]
@durchanek well that only took 5 years to clear that out ;)
